# Generated by Django 4.0.3 on 2022-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_update_servercommand_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prog_lang',
            field=models.CharField(default='cpp', max_length=10),
        ),
    ]
